"""add map preview column to routes

Revision ID: 1c899edd84a8
Revises: fa447d0988a8
Create Date: 2023-08-31 10:53:11.820527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c899edd84a8'
down_revision = 'fa447d0988a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('map_preview', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.drop_column('map_preview')

    # ### end Alembic commands ###
