"""added columns to routes

Revision ID: d05ca1c06ff9
Revises: 5d3ee0f046f6
Create Date: 2023-08-29 11:21:54.667893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd05ca1c06ff9'
down_revision = '5d3ee0f046f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waypoints', sa.PickleType(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.drop_column('waypoints')

    # ### end Alembic commands ###
